language: go
go:
    - 1.5.x
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - 1.9.x
os:
- linux
install:
- go get golang.org/x/tools/cmd/cover

branches:
  only:
  - master

script:
  - go get -t ./...
  - go build -o "marginCache" -ldflags "-w -s"
  - go test -v -cover -race ./...
