language: go
go:
    - 1.9.x
os:
- linux
install:
- go get golang.org/x/tools/cmd/cover

branches:
  only:
  - master

script:
- go get -t ./...
- go test -v -cover -race ./...
- go build -o "marginCache" -ldflags "-w -s"
